### ISSUE TITLE
How can I install Snorby on Security Onion 14.04?

### ISSUE THREAD

**Issue by f0rb1dd3n** [Security-Onion-Solutions/security-onion#1015]
I am more acquainted with Snorby interface and its reports. So I wanna know how can I install snorby on new version of Security Onion?

**Comment by dougburks** [comment]
Hi @f0rb1dd3n,

Snorby is no longer maintained by its original developer and that's why it was removed from Security Onion when we moved to 14.04.  Looking at the [commits](https://github.com/Snorby/snorby/commits/master) in 2016, Snorby has seen very little maintenance, so we recommend against installing it as doing so may introduce additional [security risks](https://github.com/Snorby/snorby/issues/439).  

Please feel free to email our [mailing list](https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
) about the data that you're looking for.  Perhaps we can suggest alternative ways of reporting on that data using tools already built into Security Onion 14.04, such as Squert or ELSA.  ELSA is advantageous in that, in addition to IDS alerts, it can also report on Bro logs, syslog, etc.

Thanks!
