### ISSUE TITLE
Setting Screen Resolution using xrandr locks up SO VM

### ISSUE THREAD

**Issue by jba3126** [Security-Onion-Solutions/security-onion#1139]
This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

I'm running a very basic setup of SO that is a fresh install.  I setup SO on VMWare ESX 5.1.  When I try to set the screen resolution via xrandr the VM locks up completely.  I can open another terminal session and reboot and things come back up.  I'm new to Security Onion so I'm sure there is a similar way to get it back up without going this route.  I'm tried to set the resolution using Ubuntu GUI and that just scrambles the screen.  Lastly I've installed VMWare tools to no avail.

Oct  9 10:55:35 sos-vm1 vmusr[3882]: [ warning] [Gtk] Unable to locate theme engine in module_path: "pixmap",
Oct  9 10:55:54 sos-vm1 kernel: init: securityonion main process (1392) terminated with status 1
Oct  9 10:57:36 sos-vm1 kernel: init: tty5 main process (1373) killed by INT signal
Oct  9 10:57:36 sos-vm1 kernel: init: tty5 main process ended, respawning

Jeff

**Comment by weslambert** [comment]
Jeff,

This issue tracker is primarily used to track issues that need to be fixed
and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get
faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,

Wes

**Comment by jba3126** [comment]
Wes,  Thank you for the response.  This is not a question, but rather an issue.  Our VMware guys have looked at this and advised this is a problem with the SO VM as we have several hundred varieties with no issues.  Please advise if I should still move this to the MailingLists?

**Comment by weslambert** [comment]
Jeff,

Yes, please move this to the mailing list.

I realize our method of managing issues differs from that of some others on
Github, but we like to refer folks who might be experiencing issues to the
mailing list, so that other members of the mailing list can benefit.  If we
verify that there is indeed an issue with Security Onion itself, then we
will open an issue on the Issue Tracker and track its resolution via our
Roadmap.

Did you install from the ISO?  If so, have you tried changing the
resolution from Settings >> Display (upper left menu).

https://groups.google.com/d/msg/security-onion/oV3qgb5Dikc/YwFVuLSrAgAJ

If you still experience issues, please post your response to the mailing
list.

Thanks,
Wes
