### ISSUE TITLE
Use remote mysql server

### ISSUE THREAD

**Issue by troptop** [Security-Onion-Solutions/security-onion#1192]
Hi,

I would like to use a remote mysql server.
When I do sosetup -f myfile -y, the process create the database in localhost and start the service.
I would like to skip this step to create the database in a remote server.

How can I do that?

Thank you
Cyril

**Comment by weslambert** [comment]
@troptop 

This is not currently supported, so we wouldn't be able to offer any advice in regard to this.

In the future, instead of opening an issue, please pose your question to the Security Onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#mailing-lists

Thanks,
Wes
