### ISSUE TITLE
create a docker of security-onion

### ISSUE THREAD

**Issue by troptop** [Security-Onion-Solutions/security-onion#1193]
Hi,
I am trying to create a docker container of security-onion server and security-onion sensor.

Is there a way to execute sosetup -f myfile -y inside of the container.
I tried diferent way and it fails.
do you have a solution?

Thank you

**Comment by weslambert** [comment]
@troptop 

You should be able to execute a command inside a Docker container by doing something like the following:

sudo docker exec -it [container_name] [command]

or 

sudo docker exec -it [container_name] sosetup -f myfile -y

In the future, if asking a question, please ensure you pose your questions to the Security Onion mailing list, instead of opening an issue:

**Comment by troptop** [comment]
Sorry I did not explain it enough.
I want to use the dockerfile to execute this command. like that the docker container will create the service when it will start.
I will put this question on the mailing list
thank you for your help
