### ISSUE TITLE
NSM: Improve the method of updating thread count in suricata.yaml

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/security-onion#1230]
The current way SO updates the threads value in the suricata.yaml overwrites 2 stats field that should be yes or no. 

Line 192:  

```  190         - stats:
 191             totals: yes       # stats for all threads merged together
 192             threads: 3
 193             deltas: no        # include delta values
```
Should be:

 ``` 190         - stats:
 191             totals: yes       # stats for all threads merged together
 192             threads: no
 193             deltas: no        # include delta values
```

Line 351:  

```345   # Stats.log contains data from various counters of the suricata engine.
 346   - stats:
 347       enabled: yes
 348       filename: stats.log
 349       append: yes       # append to file (yes) or overwrite it (no)
 350       totals: yes       # stats for all threads merged together
 351       threads: 3
```
Should be:
```345   # Stats.log contains data from various counters of the suricata engine.
 346   - stats:
 347       enabled: yes
 348       filename: stats.log
 349       append: yes       # append to file (yes) or overwrite it (no)
 350       totals: yes       # stats for all threads merged together
 351       threads: no
```

**Comment by mattmeer** [comment]
Hey Mike,

So i looked up the script that rewrites the threads value.
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/blob/fad1894f5a81ef6582608cc48a6464226e0c2235/usr/sbin/nsm_sensor_ps-restart#L530
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/blob/257c43bd152549364335760fb41d2a51edc78480/usr/sbin/nsm_sensor_ps-start#L538
Isn't the solution to this simply adding [0-9] to the end of the regex? Like this:
`s|    threads: .*[0-9]|`
From what i have tested this should limit the regex to overwriting only "threads:" values that have a digit, since the .* is greedy it should grab as many characters as possible before stopping and thus also include thread counts >9.

Kind Regards,
Matthias Meersseman

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/02/new-setup-and-nsm-packages-now.html
