### ISSUE TITLE
Avoid restarting IDS Engine where possible

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1249]
http://manual-snort-org.s3-website-us-east-1.amazonaws.com/node24.html

**Comment by dougburks** [comment]
may still need to restart barnyard

**Comment by chriswhitehat** [comment]
If possible expose the SIG HUP reload as an option vs. restart so the user can opt-in to this reload method, as it has significant implications to snort configs using AC mode rather than AC-Split.  For example, a single snort instance can use upwards of 14GB of data for in-memory rules, the reload duplicates that for a total of 28GB for as long as a session persists on the old config base.
