### ISSUE TITLE
Turn Off BRO

### ISSUE THREAD

**Issue by Idriel** [Security-Onion-Solutions/security-onion#1282]
Hi,

I have low disk space so we want to disable BRO beacuse of 2 many logs and disk usage. 

How to disable BRO or at least turn off BRO logging?
I tried changing BRO to NO in /etc/nsm/securityonion.conf (restart all services)
also I comment all networks in /opt/bro/etc/node.cfg (restart only BRO)
But I am still getting BRO logs when I look at Kibana.

**Comment by dougburks** [comment]
Hi @Idriel ,

First, please note that Security Onion should automatically start purging old logs once your disk usage reaches 90%.

Also note that Security Onion does full packet capture by default via netsniff-ng and that uses much more disk space than Bro logs do.

To answer your question, have you tried stopping Bro with `sudo broctl stop`?

For more information about disabling processes, please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/DisablingProcesses

If you have further questions, please use the mailing list instead of this Issue Tracker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
