### ISSUE TITLE
NSM: Delay watchdog checks while any other nsm_sensor_ps script runs

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1292]
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/21

**Comment by petiepooo** [comment]
As a second followup, I'm still applying this patch to my systems for five months now, and it has solved **all** issues I've had with duplicate processes due to newday and watchdog race conditions.  I have experienced **no** negative side effects from it being applied.

I am still surprised this has not been a huge issue with others, but they may be following the "periodic reboots are needed and healthy" mantra.  I like seeing high uptime numbers, at least I did prior to Spectre and all the kernel updates that has spawned...

Is there a timeframe yet for testing/releasing this?

**Comment by dougburks** [comment]
Hi @petiepooo ,

This issue is on our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/2018

Thanks!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/M9GzupEMS9E/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2018/11/securityonion-nsmnow-admin-scripts.html
