### ISSUE TITLE
Bpf-bro.conf not work

### ISSUE THREAD

**Issue by phucs** [Security-Onion-Solutions/security-onion#1418]
I want to filtering my know host in BRO IDS by using BPF-Bro
But when I update bpf-bro file and restart BRO, the alert still occurred and show on Kibana dashboard.

My bpf-bro file below:

!(src host 1.2.3.4 && dst net 4.5.0.0/16 && dst port 22)

I checked on the log file /nsm/bro/logs/current/ssh.log, still show alert.
Anyone can help me on this case.

Regards,
Phuc

**Comment by weslambert** [comment]
Hi @phucs ,

Did you unlnk bpf-bro from the main bpf.conf and create a new one as described here?

https://github.com/Security-Onion-Solutions/security-onion/wiki/BPF#granular-bpfconf

Otherwise, the filter from the main bpf.conf (nothing) would be inherited and likely overwrite whatever you supplied in bpf-bro.conf.

Please include your response and pose future questions to our mailing list, instead of creating an issue.

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes
