### ISSUE TITLE
securityonion-elastic: update Logstash config to support Wazuh 3.8 agent

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1469]
From Kevin Branch:
```
Starting with 3.8, the way Windows Wazuh agents collect Windows event logs is much different if using the eventchannel rather than the eventlog format on the agent.  That makes a huge difference in what alerts.json and archives.json will look like for Windows eventchannel inputs.
```
https://groups.google.com/d/topic/security-onion/t0rlullvD3c/discussion

Looks like this affects, at minimum, `Security` logs and `Sysmon` logs.

We'll need to update, at minimum,  `6500_ossec.conf` and `6501_ossec_sysmon.conf` to support the new format.

Also see:
https://groups.google.com/d/topic/security-onion/UtdiicGvCkw/discussion

**Comment by branchnetconsulting** [comment]
Windows Wazuh agent 3.8.2 defaults to collecting only Windows logs **Application**, **Security**, and **System**.  Of those three only **Security** is by default collected via the new **eventchannel** log format, while the legacy **eventlog** format is still by default used for the other two.  As I understand, this difference is only due to Wazuh needing to catch the rest of their ruleset up to this change.  Any logs, including non-default ones like **Sysmon**, collected by Wazuh 3.8+ via the **eventchannel** format will now be passed along with richly decoded fields that are named much differently than the limited fields formerly extracted from Windows logs.  I rather expect Wazuh will soon make **eventchannel** the default for all Windows logs period.

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/FDJ66pUgH8E/discussion

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/dbff1d6ec8fc67c730fbe9e670e8d4ea9006977f#diff-c579d5882dfbd5c7480962a7bbc486cc

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/elastic-672-now-available-for-security.html

**Comment by branchnetconsulting** [comment]
For your reference, starting with Wazuh 3.9.0 the default Windows agent configuration now uses the eventchannel log format with the associated JSON transmission for all of the legacy Windows event logs and there really is no reason I am aware of at this point to use any other log format for any Windows event logs, legacy or otherwise.

**Comment by dougburks** [comment]
Thanks @branchnetconsulting!

I've created the following issues for tracking:

https://github.com/Security-Onion-Solutions/security-onion/issues/1521

https://github.com/Security-Onion-Solutions/security-onion/issues/1522
