### ISSUE TITLE
Too many snort.log when I am doing backup...

### ISSUE THREAD

**Issue by PericoMele** [Security-Onion-Solutions/security-onion#1510]
Hi collegues:

My name is Perico. I am testing Security Onion before put it in production. My problem is when start the backup, snort keep every data transfer of the network and I usually copy more than 1 TB. I have 1,5 TB of capacitizy then fills the entire disc. I have followed this manual to suppres some rules like SNMP but I am not sure that I can suppres smb neither doesn't sniff this king of traffic in the network and keep in the snoty.log.155xxxx files.

[https://thecomputersecurityblog.wordpress.com/2015/04/23/20/](https://thecomputersecurityblog.wordpress.com/2015/04/23/20/)

Could you help me? are there some configurations to don't keep this kind of traffic?
Thanks a lot
Regards
Perico

**Comment by weslambert** [comment]
HI @PericoMele ,

The cleanup process should take care of files in /nsm, so your drive does not fill up.  If you are performing backups or moving files around, I can't really speak to that.

Please keep in mind, this issue tracker is mainly used for tracking issues confirmed via the mailing list or other sources.  If you have questions, please submit them to our mailing list, so that others in the community can more easily contribute to the conversation, and/or learn from the answers/responses.  

You can find more information about the mailing list here:

https://securityonion.readthedocs.io/en/latest/mailing-lists.html?highlight=mailing%20list#security-onion-mailing-list

Thanks,
Wes

**Comment by PericoMele** [comment]
Thanks Weslambert and I am so sorry, I thought that my post was wrong... I will read more in Mailing list.

Thanks a lot 
Regards
