### ISSUE TITLE
get the kibana dashboard outside the localhost

### ISSUE THREAD

**Issue by mounaBoo** [Security-Onion-Solutions/security-onion#1648]
Hello , 

I have recently installed Security onion for test on a virtual box, I do get the Kubana dashboard on localhost, I want to know how to get the dashboard outside the machine, I mean to change the localhost into another IP address? 

Thank you in advance;

**Comment by dougburks** [comment]
Hi @mounaBoo ,

You can run `so-allow` to allow connections from external IP addresses:
https://securityonion.readthedocs.io/en/latest/so-allow.html

If you have further questions or problems, please see:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!

**Comment by mounaBoo** [comment]
> 
> 
> Hi @mounaBoo ,
> 
> You can run `so-allow` to allow connections from external IP addresses:
> https://securityonion.readthedocs.io/en/latest/so-allow.html
> 
> If you have further questions or problems, please see:
> https://securityonion.readthedocs.io/en/latest/mailing-lists.html
> 
> Thanks!

I already did that but it's not orking in fact in the list there isn't something that allow kibana from outside, normally kibana should work from the port number 5601 but in the list you showed me there isn't such port

**Comment by dougburks** [comment]
Kibana is available via Apache reverse proxy on port 443.  So if you run `so-allow` and choose the `a` (analyst) option, that will allow connections to port 443 and you should be able to access Kibana via that port.

Again, if you have further questions or problems, please use the security-onion Google Group instead of this issue tracker:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!

**Comment by mounaBoo** [comment]
I did it and shoosed a but it still not working so my steps are: 

so-allow
select a 
enter IP adress 192.168.1.112
and validate 

but hen I go to the outside navigator and put 192.168.1.112:443 it doesn't work

**Comment by dougburks** [comment]
The IP address that you put into so-allow should be the IP address of the remote system that you want to allow to connect to Security Onion.  So, for example, if your Security Onion box has IP address 192.168.1.112 and your web browser has IP address 192.168.1.233, then you would put 192.168.1.233 into so-allow.  Then from your web browser with IP address 192.168.1.233, you would connect to https://192.168.1.112.

This issue tracker is not for support questions like this and this issue has been closed.  If you have further questions or problems, please use the security-onion Google Group instead of this issue tracker:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
