### ISSUE TITLE
Docs: Instructions for configuring docker containers (or a docker-compose file)

### ISSUE THREAD

**Issue by vanosg** [Security-Onion-Solutions/security-onion#1670]
Hi,

  First time user, trying to setup security onion on an already-existing server. Going over https://securityonion.readthedocs.io/en/latest/docker.html I see information for how to start docker containers from the ISO you provide, or an ISO where you download an SO repository, but not if I want to start SO just using docker containers. I see no reference or explanation of what each container does or provides, or which other containers they depend on. 

  What I am trying to do is run SO in my existing server environment, entirely within docker containers- without downloading a repository on the host. I don't need a script to install the docker engine for me, or download images- I'm looking for information on how to setup the containers I have downloaded myself. One "easy" way SO could provide this is via a docker-compose file, which will start and configure each container as it needs to be. Is this something the SO team would be able to provide? It would allow a one-line solution to setting up an entire SO environment within docker, without the need of downloading a repository.

Thanks for taking the time to consider this, please let me know if I can provide any additional thoughts, or contribute anything to the docs on this topic- happy to do so, if someone can get me started on the right path to get this running.

Thanks!

**Comment by dougburks** [comment]
Hi @vanosg ,

Please note that in the current Security Onion platform, only a few of the components are delivered via containers.  The remaining components (including the configuration files for those containers) are delivered via Ubuntu packages.  We do not support docker-compose files at this time.

Also note that Security Onion is not designed to be installed on top of existing servers that run other services.  It is designed to run on servers dedicated to Security Onion.

If you have further questions or problems, please use our mailing list instead of this issue tracker:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!

**Comment by vanosg** [comment]
Thanks for taking the time to reply. It might be worth adding a line stating that only a few components are dockerized to your docs, perhaps specifically somewhere on https://securityonion.net/docs/Docker. It may save future newbies from making the same mistake I did (or perhaps I just missed it if that is explicitly stated, but I scanned through pretty thoroughly I think). Thanks again!

**Comment by dougburks** [comment]
The Docker page is in the Elastic section, meaning that only the Elastic components are delivered via containers.  Other parts of the documentation explicitly mention Ubuntu packages.

To make this even more explicit, I've added the following to https://securityonion.readthedocs.io/en/latest/docker.html#images:
```
Please note that in the current platform, only a few of the components are delivered via containers. The remaining components (including the configuration files for those containers) are delivered via Ubuntu packages.
```
