### ISSUE TITLE
NET::ERR_CERT_REVOKED OSX Catalina and Chrome

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/security-onion#1705]
When connecting to SO from OSX and Chrome you get NET::ERR_CERT_REVOKED and are unable to use SO. This is because Catalina enforces the latest standards. The cert expiration can't be longer than 825 days.

**Comment by TOoSmOotH** [comment]
@dougburks I also had to add this as well to make it compliant for HH:

- extendedKeyUsage: serverAuth

**Comment by dougburks** [comment]
We don't generate our own SSL certificate, we simply use the default Ubuntu cert.  This is already fixed in Hybrid Hunter and we're not going to make any code changes for this in the current platform.  I've created a new page in the documentation and added some workarounds there:
https://securityonion.readthedocs.io/en/latest/browser.html#mac-os-x-catalina
