### ISSUE TITLE
[16.04.6.4] Logstash: fail status

### ISSUE THREAD

**Issue by forensenellanebbia** [Security-Onion-Solutions/security-onion#1743]
I created a VM for Security Onion (securityonion-16.04.6.4.iso) with VMware Workstation 14 Pro, but I can't get logstash to start. Its status always remains as **fail**.

![sostatus](https://user-images.githubusercontent.com/8271353/77793553-8fd27480-706a-11ea-85dd-fb4a5d4190c7.png)

sostat-redacted
[sostat-redacted.txt](https://github.com/Security-Onion-Solutions/security-onion/files/4395589/sostat-redacted.txt)

I installed SO as a standalone server. I tried using the command _so-elastic-restart_, installing updates by using _soup_ and with/without installing _VMware tools_. The same issue happens with VirtualBox. 
The path _/var/log/logstash_ is empty. Thanks

**Comment by dougburks** [comment]
Hi @forensenellanebbia ,

Looking at your sostat-redacted.txt, it appears you only have 4GB RAM.  We normally recommend at least 8GB RAM:
https://securityonion.readthedocs.io/en/latest/hardware.html

If you can't increase the RAM in the VM, you can try `sosetup-minimal` as it can run with less RAM.

If you have further questions or problems, please use the mailing list (https://securityonion.readthedocs.io/en/latest/mailing-lists.html) instead of this issue tracker.

Thanks!
