### ISSUE TITLE
Too many open ports

### ISSUE THREAD

**Issue by mindph** [Security-Onion-Solutions/security-onion#720]
Hello.

At default install, Security Onion has too many open ports. I installed that box standalone but still it opens a few ports for bro, syslog, ntp, sphinx and so on everything accessible from outside. This is an security issue. There should be an option for having the ports listening to localhost only, respectively it should be set to localhost when it's installed as standalone.

**Comment by dougburks** [comment]
Hi mindph,

The ports for Bro, ntp, and sphinx should not be accessible from outside the host due to the ufw (iptables) host-based firewall which should be enabled during Setup.

Also see our Post Installation page:
https://github.com/Security-Onion-Solutions/security-onion/wiki/PostInstallation

which contains a link to our Firewall page:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Firewall

If you'd like to discuss further, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
