### ISSUE TITLE
New install, Security Onion does not recognize more that 1.3 tera byte hardisk

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#787]
I am trying to install a sensor with 5 tera byte of hard disk space, When I run an install program it just recognize 1.3 tera byte hard disk. Also after finishing installation it does not find boot sector. Please help? How do I either make the OS recognize full 5 tera byte of hard disk or if its not possible how do i create smaller partition?

**Comment by dougburks** [comment]
Please see the partitioning instructions here:
https://github.com/Security-Onion-Solutions/security-onion/wiki/ProductionDeployment

If you have further questions or problems, please send them to our mailing list instead of this Issue Tracker.

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
