### ISSUE TITLE
After updating security onion snorby stopped to showing alerts in dashboard

### ISSUE THREAD

**Issue by istyakkhan84** [Security-Onion-Solutions/security-onion#841]
After updating security onion by using soup command, snorby stopped to showing alerts in dashboard.

Please could you provide the solution.

Regards
Istyak

**Comment by dougburks** [comment]
Hi Istyak,

Please see:

https://github.com/Security-Onion-Solutions/security-onion/wiki/FAQ#why-does-the-snorby-dashboard-show-all-zeroes

https://github.com/Security-Onion-Solutions/security-onion/wiki/Snorby
Snorby is now considered un-maintained and will be removed from Security Onion in the future, so you should go ahead and begin transitioning to Squert, Sguil, and/or ELSA. To disable Snorby in your existing deployment, please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/DisablingProcesses#disabling-snorby

If you have further questions or problems, please use our security-onion mailing list instead of this issue tracker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
