### ISSUE TITLE
Global log retention config

### ISSUE THREAD

**Issue by ozirus** [Security-Onion-Solutions/security-onion#850]
Hi,

I think there is a need for a global log retention config. For now; there is only for Sguild db via securityonion.conf (DAYSTOKEEP) but not for ELSA and netsniff-ng FPCs which are actually consume a lot of storage by themself. DAYSTOKEEP can trigger them also. By this feature, everyone can set this config centrally accoording their needs and budgets (for a SMB, 5 days can be the right answer for all data but for an enterprise, 30 days will be the answer etc..)

Or for an alternative; this DAYSTOKEEP can be configured for where to use; FPCs, ELSA, Sguil db etc.. Use for three of them or just FPCs and Sguild, If there is an long-term ELSA reporting need etc..

With this feature, securityonion can be more cost-effective for SMBs with fewer staff

**Comment by dougburks** [comment]
Hi ozirus,

You can already adjust these settings today:

- Full packet capture stored by netsniff-ng is controlled by CRIT_DISK_USAGE in /etc/nsm/securityonion.conf, which defaults to 90%.
- ELSA is controlled by LOG_SIZE_LIMIT in /etc/elsa_node.conf, which defaults to about 50% of your disk space.

These default settings give you about a 50/50 split where about half your disk is used for full packet capture and about the other half is used for ELSA.  Since ELSA logs don't use as much disk space as full packet capture, 50% of the disk allows a longer ELSA retention than full packet capture retention.  For example, one of my sensors has about two months of full packet capture and almost a full year of ELSA logs.

The real limiting factor for most deployments is the amount of disk space itself and most folks simply want to store full packet capture and ELSA logs for as long as their hardware allows.

If you'd like to develop additional controls, pull requests are always welcome!

Thanks!

**Comment by ozirus** [comment]
Hi Doug,

Thanks for your great explanation.

In my opinion, configuring log retention time should be based on by-day basis rather than HDD fullness rate. A lot of industry standarts like PCI, CobIT etc.. defines log retention times by day rather than HDD fullness rate. It is not a must and can be seen as an improvement. And again, it would be nice if there is also a central log retentation date parameter rather than distributed configuration files for these regulation-mandated companies. If I can find necassarry time, I'd be very happy to give necessary commit rather than just empty talk :)

Thanks again

Regards,

**Comment by dougburks** [comment]
I should also add that ELSA does support setting a number of days for retention in /etc/elsa_node.conf:

https://github.com/mcholste/elsa/blob/master/node/conf/elsa.conf#L14-L28

**Comment by ozirus** [comment]
Great. Thanks again.
