### ISSUE TITLE
Setup: ask user for HOME_NET

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#926]
default to RFC1918 private address space

sosetup should only prompt if user is configuring a network sensor

sosetup.conf needs to be updated to include this variable

**Comment by weslambert** [comment]
To confirm, is this only for a sensor?  Would there be a reason it would not be for a standalone as well?

Thanks,
Wes

**Comment by dougburks** [comment]
Hi Wes,

A standalone configuration would need to ask for HOME_NET since it is both a master server and a network sensor at the same time.

Thanks!

**Comment by weslambert** [comment]
That's what I figured.  I just wanted to be completely sure you didn't have
anything else in mind. :)

Thanks!
On Jun 24, 2016 5:56 AM, "Doug Burks" <notifications@github.com> wrote:

Hi Wes,

A standalone configuration would need to ask for HOME_NET since it is both
a master server and a network sensor at the same time.

Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Security-Onion-Solutions/security-onion/issues/926#issuecomment-228306177>,
or mute the thread
<https://github.com/notifications/unsubscribe/AQDNqMHAcbfwGpPFm5JeTbGgA1gDUSYuks5qO6nXgaJpZM4IjuJV>
.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-setup/pull/16

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-setup/pull/18

**Comment by dougburks** [comment]
Merged, thanks Wes!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/07/securityonion-setup-20120912.html
