### ISSUE TITLE
Nonstandard interface names not being detected by sosetup

### ISSUE THREAD

**Issue by cskeen** [Security-Onion-Solutions/security-onion#955]
Sosetup will not detect anything but standard interface names, which precludes the use of more friendly naming conventions (for example, eth_left or eth_right) for interfaces.

This is caused by the use of the following idiom for detecting interfaces:
cat "/proc/net/dev" | egrep "(eth|bond|wlan|br|ath|bge|mon|fe|em|p[0-5]p)[0-9]+" | awk '{print $1}' | cut -d\: -f1 |sort

Changing it to the following would resolve this issue in most cases:
cat "/proc/net/dev" | egrep "(eth|bond|wlan|br|ath|bge|mon|fe|em|p[0-5]p)\w+" | awk '{print $1}' | cut -d\: -f1 |sort

This idiom also appears in sosetup-network.

**Comment by dougburks** [comment]
Hi @cskeen ,

If you'd like, you can submit these changes via pull request:
https://github.com/Security-Onion-Solutions/securityonion-setup

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/3cef1f290993f8592383971abdd7e524c00b57ea

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

**Comment by cskeen** [comment]
Thanks! I was planning on doing a pull request when I got in this morning, but it's already done.

**Comment by weslambert** [comment]
Does the resolution of this issue (#304) close this issue (#955) -- are these the same?

https://github.com/Security-Onion-Solutions/security-onion/issues/304 

Thanks,
Wes

**Comment by dougburks** [comment]
Looking at #304, I see that @timwhisnant submitted an alternative idiom that was less strict.  

I went back and looked at where our idiom originally came from and found it in /usr/lib/nsmnow/lib-nsm-common-utils.  We've had to update it many times over the years to allow for more modern interfaces and we still don't allow for totally custom interface names like "DMZ".  

I wonder if it's time to move to a less strict idiom so that we won't have to update this anymore.  Something like this:
```
awk '/:/ {print $1}' /proc/net/dev | tr -d ':' |grep -v "^lo$" | sort
```
In words:
- search /proc/net/dev for lines that contain a colon (:) and print the first field of those lines
- remove the colons from all entries in the list
- remove the loopback interface from the list
- sort the final listing

Thoughts?

**Comment by cskeen** [comment]
I, for one, would prefer the less strict idiom. Having sosetup fail to detect an interface because it has an unusual name seems like more of a problem than the off chance of some bogus interface showing up in /proc/net/dev. In that sense, I feel that it would be better to present all the interface options (other than loopback) rather than trying to filter them for some expected convention.

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/45a23cb295411eb9bbeb8c7b4be7c6a48e81bcd5

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

**Comment by timwhisnant** [comment]
My only concern when submitting this issue was that the sguil database
would have issues parsing the interface names (there's also the concern
with validating input, bad things could occur). We've used a similar patch
in production for two+ years without issue, so *should* be good.
On Jul 6, 2016 10:05 AM, "Doug Burks" <notifications@github.com> wrote:

submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Security-Onion-Solutions/security-onion/issues/955#issuecomment-230781275>,
or mute the thread
<https://github.com/notifications/unsubscribe/AIW3W5pM_oilIP8_XM_PoNKyXE4bGzBUks5qS7YWgaJpZM4JCgJA>
.

**Comment by dougburks** [comment]
Thanks all !

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/07/securityonion-setup-20120912.html
